### ISSUE TITLE
Cancel All builds button for Development Ministry

### ISSUE THREAD

**Issue by RedOrion** [plainblack/Lacuna-Web-Client#128]

**Comment by 1vasari** [comment]
:+1:

**Comment by Fogghorn** [comment]
I'd prefer a select all option similar to the email inbox. That way I could deselect any that I wish to leave in the queue. For example I often want to leave the top item in the queue as it is partially completed and just want to cancel the rest of the queue.

**Comment by RedOrion** [comment]
:+1:

**Comment by 1vasari** [comment]
I quite like that. :+1:

**Comment by dmcbride** [comment]
So the first bit here, then, is to see if we can have a delete_many_from_queue API on the server for the web client to call.

The other fun bit is to return the newly-updated queue and repopulate the queue list in the UI with that.

I suspect this is best left until we start to reactify the building panels.

**Comment by 1vasari** [comment]
@dmcbride Agreed. I'd only want to make large changes to the code if it helps the effort to move to React. So, implementing new features on the old code is a no. That then means that I should figure out how to do that. I suspect there's a bit to it. I'll look into it...

**Comment by 1vasari** [comment]
See: #146

**Comment by 1vasari** [comment]
@dmcbride This should get closed. :santa:

**Comment by dmcbride** [comment]
@1vasari what's still missing here is the "select which ones I want to cancel somehow" - the API now will allow multiple IDs being passed in at the same time, but the client doesn't offer that to the user yet.

**Comment by 1vasari** [comment]
@dmcbride We'll Reactify the Dev min, one day. :)
