### ISSUE TITLE
Long file paths

### ISSUE THREAD

**Issue by 1vasari** [plainblack/Lacuna-Web-Client#180]
Given issue #178, we're going to end up with deeper file hierarchies happening in the `components` directory. Therefore, I think we should change `app/js/components/window/*` to just `app/js/windows/*`. `app/js/components/menu` could probably stay.The point here is that I think windows are becoming larger than just "components" and should be treated as such.

**Comment by 1vasari** [comment]
@icydee what do you think of this?

**Comment by icydee** [comment]
I suppose it comes down to what we mean by 'window', I was never entirely sure about this. What do you think of 'view' (which has the advantage of being shorter). This would give us our base level directories as
```
actions
components
stores
views
```

**Comment by icydee** [comment]
I link to the following for discussion, I am not advocating a big change is the code at this point (although now might be better than later).

http://marmelab.com/blog/2015/12/17/react-directory-structure.html

**Comment by 1vasari** [comment]
I've thought about this a bit more. I don't think it's worth changing. A bit of extra typing isn't so bad if the structure makes sense (right now, I deem it does).
