### ISSUE TITLE
File name conventions

### ISSUE THREAD

**Issue by 1vasari** [plainblack/Lacuna-Web-Client#181]
We have a few possibilities.

- `longFileName.js` (this is what is currently being used)
- `long-file-name.js` (my favourite, easiest to read)
- `LongFileName.js` (AirBnB standard)

@icydee and @dmcbride - which do you folks prefer?

**Comment by icydee** [comment]
I don't really have a preference, I adopted the first, longFileName.js simply to continue with the current approach.

I don't see much benefit going to LongFileName from where we are.

I would be ok with long-file-name

**Comment by 1vasari** [comment]
I would like to go to `long-file-name`, then. I'll do it and give ya a PR soon.

**Comment by 1vasari** [comment]
After some backwarding and forwarding in the Slack room it's been decided that no change is necessary, here. 

Closing..
