### ISSUE TITLE
Spies from flipped planet set to counter intelligence cannot be captured

### ISSUE THREAD

**Issue by Fogghorn** [plainblack/Lacuna-Web-Client#191]
When a planet is flipped the prior owners spies can be caught if the spies are set to idle. If they are set to counter intelligence they cannot be caught.

**Comment by 1vasari** [comment]
This should get filed over at the [server repository](http://github.com/plainblack/Lacuna-server-Open).

**Comment by lemming552** [comment]
And already fixed in the released code.
