### ISSUE TITLE
Only lint in development environments

### ISSUE THREAD

**Issue by 1vasari** [plainblack/Lacuna-Web-Client#197]
we could set up an environment variable ​*TLE_CLIENT_LINT*​  in a dev environment, to ensure lint checking takes place, then on production, it would not be there and so lint would not be performed.

**Comment by icydee** [comment]
oops, I have already done this, I had to get the deploy working on pt-reboot. I did this by creating a Gulp task, 'build-no-lint'. See. https://github.com/plainblack/Lacuna-Web-Client/commit/f9bdf11c5bb5f05d26221571f2865d91285b60af

**Comment by 1vasari** [comment]
I  saw. Which is why I closed it.  :)
