### ISSUE TITLE
Use Babel to compile JS so we can leverage ES6 features

### ISSUE THREAD

**Issue by 1vasari** [plainblack/Lacuna-Web-Client#94]
See [this list of ES6 features](https://github.com/lukehoban/es6features#ecmascript-6-features) to get a feel for what I'm talking about.

**Comment by dmcbride** [comment]
Careful - if this isn't supported in older browsers, we may be locking out some of our players.

**Comment by 1vasari** [comment]
It'll be fine. Babel compiles ES6 or even ES7 code down to ES5 code so that we can use new JS features without breaking older browsers.
